version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    image: app/backend
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
  frontend:
    container_name: frontend
    build:
      context: ../TasksApp_frontend
      dockerfile: Dockerfile
    links:
      - "backend"
    image: app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ../TasksApp_frontend:/usr/src/app